{
	"version": 1628252530,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/solid_plataform.png",
		"images/player-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/limit_enemy.png",
		"images/coins-sheet0.png",
		"images/coins-sheet1.png",
		"images/lifes-sheet0.png",
		"images/lifes-sheet1.png",
		"images/camerashaker-sheet0.png",
		"images/background_pattren.png",
		"images/throughsolid-sheet0.png",
		"images/sineplataform-sheet0.png",
		"images/terrain-sheet0.png",
		"images/decarations-sheet0.png",
		"images/enemyrockhead-sheet0.png",
		"images/enemyfire-sheet0.png",
		"images/decorationairplant-sheet0.png",
		"images/decorationairplant-sheet1.png",
		"images/decorationairplant-sheet2.png",
		"images/nextlevel-sheet0.png",
		"images/timersprite_font.png",
		"images/solidplataform-sheet0.png",
		"images/solid_plataformlvl2-sheet0.png",
		"images/background_pattern.png",
		"images/trampolim-sheet0.png",
		"images/trampolim-sheet1.png",
		"images/enablersignal-sheet0.png",
		"images/zoom-sheet0.png",
		"images/pause_button-sheet0.png",
		"images/pause_button-sheet1.png",
		"images/checkpoint-sheet0.png",
		"images/checkpoint-sheet1.png",
		"images/spike_trap-sheet0.png",
		"images/pig_box-sheet0.png",
		"images/pig_box-sheet1.png",
		"images/pig_box-sheet2.png",
		"images/box_hidden-sheet0.png",
		"images/dialog_box-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tutorial_assets-sheet0.png",
		"images/tutorial_text.png",
		"images/sprite2-sheet0.png",
		"images/levels-sheet0.png",
		"images/audio_state-sheet0.png",
		"images/paused_menu-sheet0.png",
		"media/hit minecraft.ogg",
		"media/sfx enemy hit.ogg",
		"media/sfx pop coin.ogg",
		"media/whoosh sfx.ogg",
		"media/whoosh2 sfx.ogg",
		"media/bloop 3 sfx.ogg",
		"media/background wait sound.ogg",
		"media/enemy box.ogg",
		"media/flag shake sfx.ogg",
		"media/hit on enemy.ogg",
		"media/rock head hit[1].ogg",
		"media/trampolim.ogg",
		"media/adhesivewombat - night shade no copyright 8-bit music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}